---
title: "Comprehensive Chromosomal Abnormality Detection"
author: "Di Shao"
date: "2024-06-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readxl)
library(arsenal)
```

```{r}
t_notb <- read_csv("clinical_and_test_results.csv")


```
## Table 1. Patient characteristics
```{r}

tab0 <- tableby(Indication ~ Age + Gestational_day, data = t_notb,digits=1)
as.data.frame(tab0)
summary(tab0)

write2word(tab0, "tab1.docx")
```
## Table 2. Summary of CNV-Seq results

```{r}
mycontrols <- tableby.control(cat.stats=c("countcellpct"))
control=mycontrols
tab1 <- tableby(Indication ~ chromosomal_status_1, data = t_notb,digits=1, control=mycontrols)
summary(tab1, text = T)

write2word(tab1, "tab2.docx")

t_notb %>% 
  mutate(size = str_extract(`结果说明`,"[0-9]+.[0-9]+[KM]b")) %>% 
    filter(Pathogenicity %in% c("P","LP")) %>%      
  filter(str_detect(chromosomal_status, "^Mic|^mic") ) %>%  view()

```
## Table 3. Comparison of detection rates of karyotype and CNV-SEQ

```{r}
tab2 <- tableby(Indication ~ chromosomal_status_2 + Karyotype_2, data = t_notb,digits=1)
summary(tab2)

write2word(tab2, "tab3.docx")
```

## Table 4. Chromosomal abnormalities detected by karyotype and their corresponding CNV-Seq results
```{r}
t_notb %>% 
  filter(Karyotype_2 == "abnormal") %>% 
  select(ID, Sample, Karyotype, Fetal_CNV, 结果说明,  Indication, Pregnancy_outcome) %>% 
  arrange(Karyotype) %>% 
  write_excel_csv("Karyotype.csv")
```
## TTable 5. pregnancy outcomes of 958 participants with follow-up data

```{r}
t_notb %>% 
  filter(chromosomal_status != "VUS") %>% 
  select(ID,Age, Sample, Gestational_day, Fetal_CNV, 结果说明, Karyotype, Indication, Pregnancy_outcome) %>% 
  arrange(Fetal_CNV) %>% 
  write_excel_csv("pCNV.csv")

```
## clinical outcomes

```{r}
mycontrols <- tableby.control(cat.stats=c("countrowpct"))
control=mycontrols
tab3 <- tableby( Pregnancy_outcome_2 ~ chromosomal_status_1, data = t_notb,digits=1, control = mycontrols)
summary(tab3)

write2word(tab3, "tab4.docx")

  
```

