---
title: "cnv-seq data cleaning"
author: "Di Shao"
date: "2024-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(tidyverse)
library(readxl)
```
### load data
```{r}
t_info <- read_xlsx("data/KY_qianduan20_20240220.xlsx")

t_cnv <- read_xlsx("data/KY_result_20240220.xlsx")

t_info <- t_info %>% 
  filter(sample_type == "S100-羊水") 


```
### get patient list
```{r}
list_p <- t_cnv %>% 
  filter(pathogenicity == "致病变异") %>% 
  pull(Sample) %>% 
  unique()


list_lp <- t_cnv %>% 
  filter(pathogenicity == "疑似致病变异") %>% 
  pull(Sample) %>% 
  unique()

intersect(list_p, list_lp)

list_lp <- setdiff(list_lp,list_p)

list_vus <- t_cnv %>% 
  filter(pathogenicity == "临床意义未明") %>% 
  pull(Sample) %>% 
  unique()

list_vus <- setdiff(list_vus, list_p)

list_vus <- setdiff(list_vus, list_lp)
```

### get cohort table  and two_or_more_pCNV list
```{r}
t_cnv %>% 
  filter(Sample %in% list_p) %>% 
  filter(pathogenicity %in% c("疑似致病变异", "致病变异")) %>% 
  group_by(Sample) %>% # 根据你要筛选的列进行分组
  filter(duplicated(Sample)|n()!=1) %>%
  ungroup() %>% 
  write_excel_csv("t_two_or_more_pCNV.csv")

t_p <- t_cnv %>% 
  filter(Sample %in% list_p) %>% 
  filter(pathogenicity %in% c("疑似致病变异", "致病变异")) %>% 
  distinct(Sample, .keep_all = T) 

t_lp <- t_cnv %>% 
  filter(Sample %in% list_lp) %>% 
  filter(pathogenicity %in% c("疑似致病变异")) %>% 
  distinct(Sample, .keep_all = T) 

t_vus <- t_cnv %>% 
  filter(Sample %in% list_vus) %>% 
    filter(pathogenicity %in% c("临床意义未明")) %>% 
  distinct(Sample, .keep_all = T) 


t_cohort <- bind_rows(t_p, t_lp, t_vus) %>% 
  left_join(t_info, by = c("Sample" = "sample_id")) %>% 
  filter(!is.na(product))

t_cnv %>% 
  t_p
write_excel_csv(t_cohort, "t_cohort.csv")

```

